name: Call another workflow

on:
	workflow_dispatch:

jobs:
	build:
		runs-on: ubuntu-latest

		steps:
			- name: Repository dispatch
			  uses: peter-evans/repository-dispatch@v1.1.2
			  with:
				  # A repo scoped Github Personal Access Token
				  token: ${{ secrets.TOTO }}
				  # A custom webhook event name
				  event-type: customEvent
				  # JSON payload with extra information about the webhook event that your action or workflow may use.
				  client-payload: '{ firstJobEvent: toto }'