name: Target for call from another workflow

on:
	repository_dispatch:
		types: [customEvent]

jobs:
	build:
		runs-on: ubuntu-latest

		steps: 
			- name: Print client payload
			  run: |
				  echo 'firstJobEvent' is ${{github.event.client_payload.firstJobEvent }}