name: Events exercices

on:
  push:
    branches: 
      # Push 2
      - dev
    # # Push 3
      - '!staging'
    # OR (Push 3)
    # branches-ignore:
    #   - staging
      # Push 4
      - 'feat*'
    # Push 5
    paths:
      - "*.ts"
      # Push 6
      - "$FOLDER/*"
